"""Initial schema

Revision ID: 7df3a938dd0d
Revises: 
Create Date: 2025-12-27 11:28:05.814781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df3a938dd0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if bookmark_count exists to avoid errors on already-patched DBs
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('relic')]
    
    if 'bookmark_count' not in columns:
        print("Alembic: Adding bookmark_count to relic table")
        op.add_column('relic', sa.Column('bookmark_count', sa.Integer(), nullable=False, server_default='0'))
    else:
        print("Alembic: bookmark_count already exists, skipping...")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
