"""introduce spaces tables

Revision ID: a39d38011b9d
Revises: 7df3a938dd0d
Create Date: 2026-03-11 21:47:36.197241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a39d38011b9d'
down_revision: Union[str, Sequence[str], None] = '7df3a938dd0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # Only create 'space' if it's missing
    if 'space' not in tables:
        op.create_table('space',
            sa.Column('id', sa.String(length=32), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('owner_client_id', sa.String(length=32), nullable=False),
            sa.Column('visibility', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['owner_client_id'], ['client_key.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_space_created_at'), 'space', ['created_at'], unique=False)
        op.create_index(op.f('ix_space_owner_client_id'), 'space', ['owner_client_id'], unique=False)
    else:
        print("Alembic Skip: Table 'space' already exists")

    # Only create 'space_access' if it's missing
    if 'space_access' not in tables:
        op.create_table('space_access',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('space_id', sa.String(length=32), nullable=False),
            sa.Column('client_id', sa.String(length=32), nullable=False),
            sa.Column('role', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['client_id'], ['client_key.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['space_id'], ['space.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('space_id', 'client_id', name='unique_space_client_access')
        )
        op.create_index(op.f('ix_space_access_client_id'), 'space_access', ['client_id'], unique=False)
        op.create_index(op.f('ix_space_access_space_id'), 'space_access', ['space_id'], unique=False)
    else:
        print("Alembic Skip: Table 'space_access' already exists")

    # Only create 'space_relics' if it's missing
    if 'space_relics' not in tables:
        op.create_table('space_relics',
            sa.Column('space_id', sa.String(length=32), nullable=False),
            sa.Column('relic_id', sa.String(length=32), nullable=False),
            sa.ForeignKeyConstraint(['relic_id'], ['relic.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['space_id'], ['space.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('space_id', 'relic_id')
        )
    else:
        print("Alembic Skip: Table 'space_relics' already exists")

    # Handle column updates safely
    relic_columns = [c['name'] for c in inspector.get_columns('relic')]
    
    # Safely alter bookmark_count
    if 'bookmark_count' in relic_columns:
        op.alter_column('relic', 'bookmark_count',
                   existing_type=sa.INTEGER(),
                   nullable=True,
                   existing_server_default=sa.text('0'))

    # Safely drop deleted_at
    if 'deleted_at' in relic_columns:
        op.drop_column('relic', 'deleted_at')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relic', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('relic', 'bookmark_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_table('space_relics')
    op.drop_index(op.f('ix_space_access_space_id'), table_name='space_access')
    op.drop_index(op.f('ix_space_access_client_id'), table_name='space_access')
    op.drop_table('space_access')
    op.drop_index(op.f('ix_space_owner_client_id'), table_name='space')
    op.drop_index(op.f('ix_space_created_at'), table_name='space')
    op.drop_table('space')
    # ### end Alembic commands ###
